# -*- coding: utf-8 -*-
"""Smoke Detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gM0fxf61KRhV-N_OPgv82glhA-iwullv
"""

!nvidia-smi

# Commented out IPython magic to ensure Python compatibility.
# clone YOLOv5 repository
# %cd /content
!git clone https://github.com/ultralytics/yolov5

# install dependencies as necessary
!pip install -r requirements.txt
!pip uninstall wandb -qy  # deprecated dependency
import torch

from IPython.display import Image, clear_output  # to display images

# clear_output()
print('Setup complete. Using torch %s %s' % (torch.__version__, torch.cuda.get_device_properties(0) if torch.cuda.is_available() else 'CPU'))

!pip install roboflow

from roboflow import Roboflow
rf = Roboflow(api_key="GRuF7VlI4fgSKCtmX0n8")
project = rf.workspace("leo-there").project("smoke-and-cigarette")
version = project.version(1)
dataset = version.download("yolov5")



# Commented out IPython magic to ensure Python compatibility.
# # train yolov5s on custom data for 25 epochs
# # time its performance
# %%time
# %cd /content/yolov5/
# !python train.py \
#   --img 416 \
#   --batch 16 \
#   --epochs 25 \
#   --data /content/smoke-and-cigarette-1/data.yaml \
#   --weights yolov5s.pt \
#   --name yolov5s_results \
#   --cache
# 
# # 返回到上一级目录
# %cd ..
#

pip install utils

from yolov5.utils.plots import plot_results  # plot results.txt as results.png
Image(filename='/content/yolov5/runs/train/yolov5s_results2/results.png', width=1000)

Image(filename='/content/yolov5/runs/train/yolov5s_results2/val_batch0_labels.jpg', width=900)